name: al_qahtani
publish_to: none
description: Al-Qahtani Flutter client consuming the Al-Qahtani Content Runtime.
version: 1.0.12+12

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
