import http from "node:http";
const MATCHES="https://api.albasritv1.workers.dev/",THEEB="https://theeb-arab-api.onrender.com",LEGACY_CINEMA="https://albas.albesriali03.workers.dev/";
const LEGACY_ORIGIN="https://www.albasritv.abrdns.com",LEGACY_REFERER=LEGACY_ORIGIN+"/2026/09/movies-series.html";
const ALLOWED_ORIGINS=new Set(["https://theeb1230-dot.github.io","http://localhost:8000","http://127.0.0.1:8000"]);
const CATEGORY_ALIASES={"أنمي":["anime","انمي","أنيمي"],"أجنبية":["english","foreign"],"عربية":["عربي","arabic"],"تركية":["تركي","turkish"],"آسيوية":["asian","كوري","ياباني"],"هندية":["هندي","indian"],"رمضان":["رمضانية"]};
function cors(req,res){const origin=String(req.headers.origin||"");if(origin&&ALLOWED_ORIGINS.has(origin))res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","GET,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type,Range");res.setHeader("Access-Control-Expose-Headers","Content-Length,Content-Range,Accept-Ranges,Content-Type")}
function send(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(data))}
function log(event,data={}){console.log(JSON.stringify({ts:new Date().toISOString(),event,...data}))}
async function jfetch(url,init={},timeout=45000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...init,signal:ctl.signal,cache:"no-store"}),text=await r.text();let data=null;try{data=JSON.parse(text)}catch{}return{r,data,text}}finally{clearTimeout(t)}}
function legacyHeaders(token=""){const h={Accept:"application/json",Origin:LEGACY_ORIGIN,Referer:LEGACY_REFERER,"X-BSR-Page":"/2026/09/matches.html"};if(token)h["X-BSR-Token"]=token;return h}
async function matchSession(){const x=await jfetch(MATCHES+"session",{headers:legacyHeaders()});if(!x.r.ok||!x.data?.token)throw new Error("MATCH_SESSION_"+x.r.status);return x.data.token}
async function matches(){const token=await matchSession(),x=await jfetch(MATCHES,{headers:legacyHeaders(token)});if(!x.r.ok)throw new Error("MATCH_LIST_"+x.r.status);return x.data}
async function matchServers(target){const u=new URL(target);if(u.origin!==new URL(MATCHES).origin)throw new Error("BAD_MATCH_TARGET");const token=await matchSession(),x=await jfetch(u.href,{headers:legacyHeaders(token)});if(!x.r.ok)throw new Error("MATCH_SERVERS_"+x.r.status);return x.data}
function mapLibrary(items=[]){return items.map(i=>({title:i.title,img:i.image||"",is_series:i.content_type!=="movie",href:"theeb:canonical:"+i.id,year:i.year||null}))}
function encodeDiscovery(i,query=""){return encodeURIComponent(JSON.stringify({provider:i.provider,id:i.provider_series_id,source:i.source_url||"",type:i.content_type||i.type||"series",title:i.title||i.display_title||"",display_title:i.display_title||i.title||"",query:query||""}))}
function mapDiscovered(items=[],query=""){return items.map(i=>({title:i.display_title||i.title,img:i.image||"",is_series:(i.content_type||i.type)!=="movie",href:"theeb:discover:"+encodeDiscovery(i,query),year:i.year||null}))}
function mapLegacy(items=[]){return items.map(i=>{const raw=i.href||i.url||i.link||"";return{title:i.title||i.name||"بدون عنوان",img:i.img||i.image||i.poster||"",is_series:i.is_series!==false,href:raw?"legacy:"+encodeURIComponent(raw):"",year:i.year||null}}).filter(i=>i.href)}
async function legacySession(){const x=await jfetch(LEGACY_CINEMA+"session",{headers:{Accept:"application/json",Origin:LEGACY_ORIGIN,Referer:LEGACY_REFERER}},15000);return x.r.ok&&x.data?.token?String(x.data.token):""}
async function legacyCinema(action,params={}){const token=await legacySession();if(!token)return[];const q=new URLSearchParams({action,token,...params}),x=await jfetch(LEGACY_CINEMA+"?"+q,{headers:{Accept:"application/json",Origin:LEGACY_ORIGIN,Referer:LEGACY_REFERER}},30000);return x.r.ok&&x.data?.status==="success"?mapLegacy(x.data.data||[]):[]}
async function legacyDetails(url){const token=await legacySession();if(!token)throw new Error("LEGACY_SESSION");const q=new URLSearchParams({action:"series",series:url,token}),x=await jfetch(LEGACY_CINEMA+"?"+q,{headers:{Accept:"application/json",Origin:LEGACY_ORIGIN,Referer:LEGACY_REFERER}},45000);if(!x.r.ok||x.data?.status!=="success")throw new Error("LEGACY_DETAILS_"+x.r.status);return x.data}
async function cinemaSearch(q){let x=await jfetch(THEEB+"/v1/search?q="+encodeURIComponent(q),{headers:{Accept:"application/json"}},45000),items=x.data?.data?.items||[];if(items.length)return{status:"success",source:"library",data:mapLibrary(items)};x=await jfetch(THEEB+"/v1/discover?q="+encodeURIComponent(q),{headers:{Accept:"application/json"}},60000);items=x.data?.data?.items||[];if(items.length)return{status:"success",source:"discover",data:mapDiscovered(items,q)};const legacy=await legacyCinema("search",{q});return{status:"success",source:legacy.length?"legacy":"empty",data:legacy}}
async function cinemaCategory(type,name,url=""){const kind=type==="movie"?"فيلم":"مسلسل",queries=[name,kind+" "+name,name+" "+kind,...(CATEGORY_ALIASES[name]||[])],uniq=[...new Set(queries.filter(Boolean))],settled=await Promise.allSettled(uniq.map(q=>jfetch(THEEB+"/v1/discover?q="+encodeURIComponent(q),{headers:{Accept:"application/json"}},40000))),seen=new Set(),merged=[];for(const result of settled){if(result.status!=="fulfilled")continue;for(const item of(result.value.data?.data?.items||[])){const key=String(item.provider||"")+":"+String(item.provider_series_id||"");if(!key||seen.has(key))continue;seen.add(key);merged.push(item);if(merged.length>=36)break}if(merged.length>=36)break}if(merged.length)return{status:"success",source:"discover",data:mapDiscovered(merged)};const legacy=url?await legacyCinema("genre",{genre:url,p:"1"}):[];return{status:"success",source:legacy.length?"legacy":"empty",data:legacy}}
async function canonicalDetails(id){const[s,e]=await Promise.all([jfetch(THEEB+"/v1/series/"+id,{headers:{Accept:"application/json"}},45000),jfetch(THEEB+"/v1/series/"+id+"/episodes",{headers:{Accept:"application/json"}},45000)]);if(!s.r.ok)throw new Error("SERIES_"+s.r.status);const series=s.data?.data||{},eps=e.data?.data?.items||[];return{status:"success",movie_title:series.title||"",poster:series.image||"",episodes:eps.map(x=>({num:x.episode_number||x.id,link:"theeb:episode:"+x.id,id:x.id,watch_available:x.watch_available,download_available:x.download_available}))}}
async function findCanonicalByTitle(title){if(!title)return null;const x=await jfetch(THEEB+"/v1/search?q="+encodeURIComponent(title),{headers:{Accept:"application/json"}},30000),items=x.data?.data?.items||[],norm=String(title).trim().toLowerCase(),exact=items.find(i=>String(i.title||"").trim().toLowerCase()===norm);return exact?.id||items[0]?.id||null}
async function tryImportCandidate(p){let created;try{created=await jfetch(THEEB+"/v1/imports",{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({provider:p.provider,provider_series_id:String(p.id)})},45000)}catch(e){log("import_transport_failed",{provider:p.provider,id:p.id,error:String(e)});return null}if(!created.r.ok||!created.data?.data?.job_id){log("import_rejected",{provider:p.provider,id:p.id,status:created.r.status});return null}const jobId=created.data.data.job_id;for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,i<2?400:1000));const job=await jfetch(THEEB+"/v1/imports/"+encodeURIComponent(jobId),{headers:{Accept:"application/json"}},12000),d=job.data?.data;if(d?.status==="completed"&&d.result?.canonical_series_id)return d.result.canonical_series_id;if(["failed","cancelled"].includes(d?.status)){log("import_terminal",{provider:p.provider,id:p.id,status:d.status});return null}}log("import_timeout",{provider:p.provider,id:p.id});return null}
async function discoverAlternatives(query){if(!query)return[];const x=await jfetch(THEEB+"/v1/discover?q="+encodeURIComponent(query),{headers:{Accept:"application/json"}},60000);return(x.data?.data?.items||[]).map(i=>({provider:i.provider,id:i.provider_series_id,source:i.source_url||"",type:i.content_type||i.type||"series",title:i.title||i.display_title||query,display_title:i.display_title||i.title||query,query}))}
async function discoveredDetails(ref){const primary=JSON.parse(decodeURIComponent(ref)),lookup=primary.query||primary.title||primary.display_title||"",alts=await discoverAlternatives(lookup).catch(()=>[]),seen=new Set(),candidates=[];for(const p of[primary,...alts]){const key=String(p.provider)+":"+String(p.id);if(!p.provider||!p.id||seen.has(key))continue;seen.add(key);candidates.push(p)}log("detail_candidates",{query:lookup,candidates:candidates.map(p=>p.provider+":"+p.id)});for(const p of candidates.slice(0,4)){const canonical=await tryImportCandidate(p);if(canonical){log("import_fallback_success",{provider:p.provider,id:p.id,canonical});return canonicalDetails(canonical)}}const canonicalId=await findCanonicalByTitle(primary.title||lookup);if(canonicalId)return canonicalDetails(canonicalId);throw new Error("DETAILS_UNAVAILABLE")}
async function episodePlayback(id){const episodeId=Number(id);if(!Number.isSafeInteger(episodeId)||episodeId<1)throw new Error("BAD_EPISODE");const created=await jfetch(THEEB+"/v1/playback/sessions",{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({canonical_episode_id:episodeId,quality:"auto",client:{platform:"web",version:"al-qahtani-web"}})},60000);if(!created.r.ok)throw new Error("PLAYBACK_CREATE_"+created.r.status);let session=created.data?.data;if(!session)throw new Error("PLAYBACK_EMPTY");for(let i=0;i<10&&session.state==="planning";i++){await new Promise(r=>setTimeout(r,750));const poll=await jfetch(THEEB+"/v1/playback/sessions/"+encodeURIComponent(session.id),{headers:{Accept:"application/json"}},15000);if(poll.data?.data)session=poll.data.data}if(session.state!=="ready"||!session.id)return{status:"error",message:"NO_PLAYABLE_SOURCE"};const downloads=await jfetch(THEEB+"/v1/episodes/"+episodeId+"/download-options",{headers:{Accept:"application/json"}},15000).catch(()=>null);return{status:"success",media_path:"/api/cinema/media?session="+encodeURIComponent(session.id),media_type:"stream",is_iframe:false,playback_session_id:session.id,download_options:downloads?.data?.data?.items||[]}}
async function proxyMedia(req,res,sessionId){if(!/^[A-Za-z0-9._:-]{1,200}$/.test(sessionId))return send(res,400,{status:"error",message:"BAD_SESSION"});const headers={Accept:"*/*"};if(req.headers.range)headers.Range=req.headers.range;const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),60000);try{const upstream=await fetch(THEEB+"/v1/playback/sessions/"+encodeURIComponent(sessionId)+"/media",{headers,signal:ctl.signal,redirect:"follow",cache:"no-store"});if(!upstream.ok&&upstream.status!==206)return send(res,upstream.status,{status:"error",message:"MEDIA_UPSTREAM_"+upstream.status});cors(req,res);for(const h of["content-type","content-length","content-range","accept-ranges","etag","last-modified"]){const v=upstream.headers.get(h);if(v)res.setHeader(h,v)}res.setHeader("Cache-Control","no-store");res.statusCode=upstream.status;if(!upstream.body)return res.end();for await(const chunk of upstream.body)res.write(chunk);res.end()}catch(e){if(!res.headersSent)return send(res,502,{status:"error",message:"MEDIA_PROXY_FAILED"});res.destroy(e)}finally{clearTimeout(t)}}
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}const u=new URL(req.url,"http://localhost"),started=Date.now();try{if(u.pathname==="/health")return send(res,200,{status:"ok"});if(u.pathname==="/api/matches")return send(res,200,await matches());if(u.pathname==="/api/matches/servers")return send(res,200,await matchServers(u.searchParams.get("url")||""));if(u.pathname==="/api/cinema/search")return send(res,200,await cinemaSearch((u.searchParams.get("q")||"").trim()));if(u.pathname==="/api/cinema/category")return send(res,200,await cinemaCategory(u.searchParams.get("type")||"series",(u.searchParams.get("name")||"").trim(),u.searchParams.get("url")||""));if(u.pathname==="/api/cinema/media")return proxyMedia(req,res,u.searchParams.get("session")||"");if(u.pathname==="/api/cinema/details"){const ref=u.searchParams.get("ref")||"";if(ref.startsWith("theeb:canonical:"))return send(res,200,await canonicalDetails(ref.split(":").pop()));if(ref.startsWith("theeb:discover:"))return send(res,200,await discoveredDetails(ref.slice("theeb:discover:".length)));if(ref.startsWith("theeb:episode:"))return send(res,200,await episodePlayback(ref.split(":").pop()));if(ref.startsWith("legacy:"))return send(res,200,await legacyDetails(decodeURIComponent(ref.slice(7))));return send(res,400,{status:"error",message:"BAD_REFERENCE"})}return send(res,404,{error:"NOT_FOUND"})}catch(e){log("request_failed",{path:u.pathname,ms:Date.now()-started,error:String(e?.message||e)});return send(res,502,{status:"error",message:String(e?.message||"UPSTREAM_FAILED")})}});server.listen(Number(process.env.PORT||3000),"0.0.0.0",()=>console.log("Al-Qahtani backend listening"));